on:
  workflow_dispatch:

jobs:
  update_stats_image:
    runs-on: ubuntu-latest
    steps:
      - uses: snaka/Profile-Readme-WakaTime@feature/avoid-unnecessary-commits
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: main
